#! /bin/bash

DOCKER_NAME="arxiv-papers-classification"
CONTAINER_NAME=$USER"-arxiv-papers-classification"
SRC="." # folder to propulse in docker container
DOCKER_USER_ID=$(id -u) # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=$(id -g)
CONTAINER_PORT=7860 # used in launch_container file
INNER_PORT=7860 